//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBS3000Dashboard.Vis.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-DE")]
        public global::System.Globalization.CultureInfo DefaultLanguage {
            get {
                return ((global::System.Globalization.CultureInfo)(this["DefaultLanguage"]));
            }
            set {
                this["DefaultLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string languageSelectionEnable {
            get {
                return ((string)(this["languageSelectionEnable"]));
            }
            set {
                this["languageSelectionEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Activate_de {
            get {
                return ((bool)(this["Activate_de"]));
            }
            set {
                this["Activate_de"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Activate_en {
            get {
                return ((bool)(this["Activate_en"]));
            }
            set {
                this["Activate_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Activate_es {
            get {
                return ((bool)(this["Activate_es"]));
            }
            set {
                this["Activate_es"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Activate_fr {
            get {
                return ((bool)(this["Activate_fr"]));
            }
            set {
                this["Activate_fr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TestModeActive {
            get {
                return ((bool)(this["TestModeActive"]));
            }
            set {
                this["TestModeActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UpdateIntervalOpModeChart {
            get {
                return ((int)(this["UpdateIntervalOpModeChart"]));
            }
            set {
                this["UpdateIntervalOpModeChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int UpdateIntervalIoNioPartsChart {
            get {
                return ((int)(this["UpdateIntervalIoNioPartsChart"]));
            }
            set {
                this["UpdateIntervalIoNioPartsChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int UpdateIntervalTemperatureChart {
            get {
                return ((int)(this["UpdateIntervalTemperatureChart"]));
            }
            set {
                this["UpdateIntervalTemperatureChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UpdateIntervalCommonErrorsChart {
            get {
                return ((int)(this["UpdateIntervalCommonErrorsChart"]));
            }
            set {
                this["UpdateIntervalCommonErrorsChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UpdateIntervalOutputChart {
            get {
                return ((int)(this["UpdateIntervalOutputChart"]));
            }
            set {
                this["UpdateIntervalOutputChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayOpMode {
            get {
                return ((int)(this["HoursToDisplayOpMode"]));
            }
            set {
                this["HoursToDisplayOpMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayIoNioParts {
            get {
                return ((int)(this["HoursToDisplayIoNioParts"]));
            }
            set {
                this["HoursToDisplayIoNioParts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayTemperature {
            get {
                return ((int)(this["HoursToDisplayTemperature"]));
            }
            set {
                this["HoursToDisplayTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayCommonErrors {
            get {
                return ((int)(this["HoursToDisplayCommonErrors"]));
            }
            set {
                this["HoursToDisplayCommonErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayOutput {
            get {
                return ((int)(this["HoursToDisplayOutput"]));
            }
            set {
                this["HoursToDisplayOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int UpdateIntervalPcbCameraSelfCheckChart {
            get {
                return ((int)(this["UpdateIntervalPcbCameraSelfCheckChart"]));
            }
            set {
                this["UpdateIntervalPcbCameraSelfCheckChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int HoursToDisplayPcbCameraSelfCheckChart {
            get {
                return ((int)(this["HoursToDisplayPcbCameraSelfCheckChart"]));
            }
            set {
                this["HoursToDisplayPcbCameraSelfCheckChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MESxxx")]
        public string MachineName {
            get {
                return ((string)(this["MachineName"]));
            }
            set {
                this["MachineName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpModeChartVisible {
            get {
                return ((bool)(this["OpModeChartVisible"]));
            }
            set {
                this["OpModeChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OkNokChartVisible {
            get {
                return ((bool)(this["OkNokChartVisible"]));
            }
            set {
                this["OkNokChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemperatureChartVisible {
            get {
                return ((bool)(this["TemperatureChartVisible"]));
            }
            set {
                this["TemperatureChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutputChartVisible {
            get {
                return ((bool)(this["OutputChartVisible"]));
            }
            set {
                this["OutputChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CommonErrorsChartVisible {
            get {
                return ((bool)(this["CommonErrorsChartVisible"]));
            }
            set {
                this["CommonErrorsChartVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PcbCameraSelfCheckChartVisible {
            get {
                return ((bool)(this["PcbCameraSelfCheckChartVisible"]));
            }
            set {
                this["PcbCameraSelfCheckChartVisible"] = value;
            }
        }
    }
}
